apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api.yaml
  - redis.yaml
  - ingress.yaml

namespace: fast-sentiment

commonLabels:
  app.kubernetes.io/part-of: fast-sentiment

# Define variables that need to be replaced during deployment
vars:
  - name: DOCKER_REGISTRY
    objref:
      kind: Deployment
      name: fast-sentiment
      apiVersion: apps/v1
    fieldref:
      fieldpath: spec.template.spec.containers[0].image